"""
L-BFGS implementation

This module provides an implementation of the L-BFGS algorithm.

Author: Jonas Lucka
Date: 2026
"""

from collections import deque
import numpy as np
from mathematical_optimization.line_search import wolfe_line_search


def two_loop_recursion(grad_fk, s_history, y_history):
    """
    L-BFGS two-loop recursion method which is based on Algorithm 7.4 in
    Nocedal and Wright: Numerical Optimization 2nd edition

    Parameters
    ----------
    grad_fk : ndarray
        Current gradient vector ∇f(x_k).

    s_hist : sequence of ndarray
        Stored displacement vectors
        s_i = x_{i+1} - x_i
        from the previous iterations.

    y_hist : sequence of ndarray
        Stored gradient-difference vectors
        y_i = ∇f(x_{i+1}) - ∇f(x_i)
        corresponding to the vectors in s_hist.

    Returns
    -------
    r : ndarray
        The vector H_k @ grad, where H_k is the current L-BFGS inverse
        Hessian approximation.
    """

    q = grad_fk.copy()

    # rho_i = 1 / (y_i^T s_i)
    rho_history = [
        1.0 / np.dot(y, s)
        for s, y in zip(s_history, y_history)
    ]

    alpha_history = []

    # First loop
    # Backward loop
    for s, y, rho in zip(
        reversed(s_history),
        reversed(y_history),
        reversed(rho_history)
    ):
        alpha = rho * np.dot(s, q)
        alpha_history.append(alpha)
        q -= alpha * y

    # H_k^0 = gamma_k*I
    # If there is no history, use I.
    if s_history:
        s_last = s_history[-1]
        y_last = y_history[-1]

        yy = np.dot(y_last, y_last)

        if yy > 0.0:
            gamma = np.dot(s_last, y_last) / yy
        else:
            gamma = 1.0
        if gamma <= 0.0 or not np.isfinite(gamma):
            gamma = 1.0
    else:
        gamma = 1.0

    # H_k^0*q
    r = gamma * q

    # Second loop
    # Forward loop
    for s, y, rho, alpha in zip(
        s_history,
        y_history,
        rho_history,
        reversed(alpha_history)
    ):
        beta = rho * np.dot(y, r)
        r += s * (alpha - beta)
    return r


def optimize_lbfgs(f, grad_f, x0, m=10, tol=1e-5, max_it=100, return_history=False, alpha_max=250):
    """
    L-BFGS method which is based on Algorithm 7.5 in
    Nocedal and Wright: Numerical Optimization 2nd edition
    The step length is obtained from a strong Wolfe line search.

    Parameters
    ----------
    f : callable
        Objective function.

    grad_f : callable
        Gradient of f.

    x0 : array_like
        Starting point.

    m : int, optional
        Maximum number of correction pairs (s_i, y_i) stored in memory.

    tol : float, optional
        Convergence tolerance.
    
    max_it : int, optional
        Maximum number of iterations.

    return_history: bool, optional
        If True, return the sequence of iterates in addition to the
        approximate minimizer.
        If False, only the approximate minimizer is returned.

    max_alpha : float, optional
        Maximum allowed step length for the line search.


    Returns
    -------
    x : ndarray
        Approximate minimizer.

    history : list of ndarray
        Sequence of iterates generated by the algorithm, including the initial point x0.
        This is returned only if return_history is True.


    Raises
    ------
    RuntimeError
        If the algorithm reaches max_iter iterations without satisfying
        the convergence criterion.
    """

    x = np.asarray(x0, dtype=float)
    g = grad_f(x)

    s_hist = deque(maxlen=m)
    y_hist = deque(maxlen=m)

    history = [x.copy()]

    for _ in range(max_it):
        # Check the convergence criterion.
        if np.linalg.norm(g) < tol:
            break

        # d_k = -H_k * grad
        d = -two_loop_recursion(g, s_hist, y_hist)

        # Strong Wolfe line search
        alpha = wolfe_line_search(f, grad_f, x, d, alpha_max=alpha_max)

        # Update everything
        x_new = x + alpha * d
        g_new = grad_f(x_new)
        s = x_new - x
        y = g_new - g

        # Curvature condition
        if np.dot(s, y) > 1e-10:
            s_hist.append(s)
            y_hist.append(y)

        # Prepare for the next iteration
        x = x_new
        g = g_new
        history.append(x.copy())

    else:
        raise RuntimeError(
            "L-BFGS failed to converge within "
            f"max_iter={max_it} iterations."
        )

    if return_history:
        return x, history
    return x
